action_id: trunk-single-player-auto-upgrade
date: 2024-05-31 01:45:04
run: trunk upgrade cli --single-player-only -n --no-progress --on-upgrade=false --allow-daemon-start=false
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1717119904
full_timestamp:
  nanos: 144478000
  seconds: 1717119904
trunk_version: 1.22.1
