action_id: trunk-single-player-auto-on-upgrade
date: 2024-06-02 11:56:54
run: trunk on-upgrade --single-player-only -n --no-progress --allow-daemon-start=false --print-summary --scope=check,plugins,runtimes,tools
run_from: ""
trigger: schedule 24h+5m
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1717329414
full_timestamp:
  nanos: 844876000
  seconds: 1717329414
trunk_version: 1.22.1
