@echo off
REM Generated by trunk tool 'osv-scanner'
set PATH=C:\Users\81909\AppData\Local\trunk\tools\osv-scanner\1.7.4-8a60135bbc4d37863b36b65e36aee883;C:\Users\81909\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\81909\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b osv-scanner %*
