@echo off
REM Generated by trunk tool 'svgo'
set NODE_PATH=C:\Users\81909\AppData\Local\trunk\tools\svgo\3.3.2-c7030f14a69c4415b8a248cfb9b9b312/node_modules
set PATH=C:\Users\81909\AppData\Local\trunk\tools\svgo\3.3.2-c7030f14a69c4415b8a248cfb9b9b312/node_modules/.bin;C:\Users\81909\AppData\Local\trunk\tools\node\18.12.1-ee91e409de31a08a96aaff7f742f83b4/bin;C:\Users\81909\AppData\Local\trunk\tools\node\18.12.1-ee91e409de31a08a96aaff7f742f83b4;C:\Users\81909\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\81909\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set HOME=%HOME%
if not defined HOME set HOME=

start /w /b svgo %*
