@echo off
REM Generated by trunk tool 'trufflehog'
set PATH=C:\Users\81909\AppData\Local\trunk\tools\trufflehog\3.76.3-9df1b9ece96a45f9d060c5c378241848;C:\Users\81909\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\81909\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trufflehog %*
