action_id: trunk-whoami
date: 2024-06-02 12:52:00
run: trunk whoami
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 0
  out: "\x1b[92m✔ Logged in as RyoTonegawa (tonegawa622@gmail.com)\x1b[0m\r\n"
  err: ""
timestamp: 1717332720
full_timestamp:
  nanos: 495945000
  seconds: 1717332720
trunk_version: 1.22.1
