action_id: trunk-share-with-everyone
date: 2024-06-02 11:51:55
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-share-with-everyone\r\n"
  err: ""
timestamp: 1717329115
full_timestamp:
  nanos: 359698000
  seconds: 1717329115
trunk_version: 1.22.1
action_output:
  notifications_to_delete:
    - trunk-share-with-everyone
