action_id: trunk-share-with-everyone
date: 2024-05-29 00:34:28
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-share-with-everyone\r\n"
  err: ""
timestamp: 1716942868
full_timestamp:
  nanos: 19610000
  seconds: 1716942868
trunk_version: 1.22.1
action_output:
  notifications_to_delete:
    - trunk-share-with-everyone
