action_id: trunk-share-with-everyone
date: 2024-05-31 00:45:04
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-share-with-everyone\r\n"
  err: ""
timestamp: 1717116304
full_timestamp:
  nanos: 374471000
  seconds: 1717116304
trunk_version: 1.22.1
action_output:
  notifications_to_delete:
    - trunk-share-with-everyone
